version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPOSITORY: "brain-tasks-app"
    EKS_CLUSTER_NAME: "project3-devops-eks"

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/v1.36.3/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      -  'echo "ECR URI: $ECR_URI"'
- 'echo "Image tag: $IMAGE_TAG"'

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo "Configuring kubectl for EKS..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - echo "Updating Kubernetes deployment image..."
      - sed -i "s|image: .*|image: $ECR_URI:$IMAGE_TAG|" k8s/deployment.yaml
      - echo "Applying Kubernetes Deployment..."
      - kubectl apply -f k8s/deployment.yaml
      - echo "Applying Kubernetes Service..."
      - kubectl apply -f k8s/service.yaml
      - echo "Waiting for deployment rollout..."
      - kubectl rollout status deployment/brain-tasks-app --timeout=180s
      - echo "Deployment completed successfully!"
      - kubectl get pods
      - kubectl get service brain-tasks-service

artifacts:
  files:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - Dockerfile
