apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-044f870a3f592e1f9,subnet-0b9e7a25b23390279,subnet-0552a98e0c9d8ec31
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
